### PR TITLE
Support GHC 9.2

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
The build failure with GHC 7.10.3 is due to https://github.com/tsurucapital/vector-th-unbox/issues/7.

I see several options for now:

* [ ] Wait until https://github.com/tsurucapital/vector-th-unbox/issues/7 is resolved.
* [ ] Drop support for GHC 7.10.
* [ ] Migrate the benchmarks from `criterion` to `tasty-bench` to avoid the dependency on `vector-th-unboxed`.

Any preferences?

**Comment by chrisdone** [comment]
Looks like the first option panned out.

I think migrating to gauge would also be fine, but not a big priority unless someone is especially excited about gauge.

Explicitly dropping support for GHC 7.10 seems unnecessary at this point. It’s just a benchmark failure. That’s why I set it to allow fail, but didn’t explicitly update the base lower bound.

**Comment by chrisdone** [comment]
Merging the GHC 9 support, thanks!

**Comment by sjakobi** [comment]
> It’s just a benchmark failure. That’s why I set it to allow fail, but didn’t explicitly update the base lower bound.

Oh, I hadn't seen that. With `haskell-ci`, if you want to preserve a certain setting, it's best to put it into the `cabal.haskell-ci` config, e.g.

```
allow-failures: == 7.10.3
```

Future runs of `haskell-ci regenerate` will then take this setting into account.

BTW, could you publish the bumped bound on `base` via a Hackage revision? Thanks!

**Comment by chrisdone** [comment]
I've published a new revision.

**Comment by chrisdone** [comment]
Thanks @sjakobi Looks like lucid didn't need any changes to work on GHC 9.2, which is good.

**Pull request merged**
