### PR TITLE
Monadic ToHTML

### PR DESCRIPTION
**Pull request by athanclark**
`HtmlT` is a monad transformer that represents Html, within some monadic context - therefore, any `foo :: HtmlT m ()` is not _just_ Html, but Html generated in the context `m`. I suggest that the monadic context be a second type parameter in the `ToHTML` class, via a multiparam type class (without fundeps). In most circumstances, a subject data type will have a pure representation as Html, and their instances would reflect that with `instance ToHTML m Foo where ...`; and so every monad would work when used as that context. But what if you wanted to print out some data that had a `STRef` or `IORef` inside it? Or a number of things could be involved that would leave one desired different Html representations for different monad instances.

Anyway, that's my rationale. The code _should_ work as expected, but I haven't thoroughly tested it.

### CODE REVIEW

**Comment by phadej** [comment]
- I not sure that MPTC without FunDep is a good idea
- I'm not sure that instances for base type is great idea either. For comparison `blaze-markup` has instances for numeric types, but not for composites (except `ToMarkup [Markup]`). I'm pretty sure someone will dislike the "default" behaviour. (e.g. `ToHtml Day` would definitely make long and diverging bikeshedding thread). So i'd rather stick with very clear cut instances. IMHO `Float` / `Double` instances are not clear. You almost always want to round them to something. Providing a good collection of combinators, starting with `toHtmlShow` is better approach.

This PR does two things, so I'd advice to split it into two PRs; to keep discussion focused

**Comment by athanclark** [comment]
Right on, I'll hop to it.

As far as the first concern - is your specific concern MPT w/o fundeps? Or just the MPT in general?

As the second, I understand - html isn't a target serialization for arbitrary data - more like... a documenting framework for serialized data, or something. Idk, either way I think I understand.

Would you rather have me split this into `lucid-class` or something?

**Comment by chrisdone** [comment]
I think that changing the class would piss off a lot of people who'd have to change their code. Given that this can be just another class like `toHtmlM` or whatever, that would probably be an easier route.

**Comment by chrisdone** [comment]
I'd agree on `Float`/`Double` instances not being appropriate; someone is likely to be surprised and complain.

**Comment by athanclark** [comment]
Alright, sorry about this. I guess maybe the documentation could just get amended, s.t. it's a class for "HTML show-able data types, in a pure context"? I'll toss this in a separate package. Thanks for checking up on this

**Pull request closed without merging**
