### PR TITLE
add a utility to generalize the underlying monad from Identity

### PR DESCRIPTION
**Pull request by ggreif**
(I am looking at you diagrams-svg!)

Obviously this necessitates a minor version bump.

### CODE REVIEW

**Comment by athanclark** [comment]
This is actually generalized with #37:

```haskell
import Control.Monad.Morph

relaxHtmlT :: Monad m => HtmlT Identity a -> HtmlT m a
relaxHtmlT = hoist go
  where
    go :: Monad m => Identity a -> m a
    go = return . runIdentity
```

**Comment by ggreif** [comment]
@athanclark I see your PR is merged, I'll come up with a new patch. Thanks for the heads-up!

**Comment by jeffreyrosenbluth** [comment]
@ggreif 
Could you explain how this might useful for diagrams-svg?

**Comment by ggreif** [comment]
@jeffreyrosenbluth `diagrams-svg` generally produces values of type `HtmlT Identity a` but to fit them into a general `lucid` context you want a more parametric type `HtmlT m a`. The suggested function will do the "impedance matching" and it is safe.

**Pull request merged**
