### PR TITLE
Add MonadReader and MonadState instances

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
ping @chrisdone, is there something wrong with this PR?

**Comment by chrisdone** [comment]
Would this instance be usable instead?
``` haskell
instance Monad m => MonadReader r (HtmlT (ReaderT r m)) where
  ask = lift ask
  local f (HtmlT a) = HtmlT (local f a)
```

**Comment by phadej** [comment]
@chrisdone why'd you prefer that, it's strictly less general?

**Comment by chrisdone** [comment]
Just because it satisfies the functional dependency which has good type inference. I think the incoherent instance is okay too, but it's a trade-off. But if this one satisfies your use-case then it might be better. With this you can trivially derive newtypes for your app:

``` haskell
newtype MyApp m a = MyApp (HtmlT (ReaderT () m) a)
  deriving (Applicative,Functor,Monad,MonadReader ())
```

**Comment by phadej** [comment]
@chrisdone it's not incoherent, the coverage is undecidable, that's different. I use instance as proposed (since around when PR is made), and hand't any problems with type-inference.

**Comment by chrisdone** [comment]
Sorry, I meant undecidable.

**Pull request merged**
