### PR TITLE
add makeElementSvg

### PR DESCRIPTION
**Pull request by jeffreyrosenbluth**
I realized that my lucid-svg package is broken and I need this
function to fix it. I would very much appreciate it if you would
merge this in as soon as possible. I hate having a bug in my
hackage package.

thanks
jeff

### CODE REVIEW

**Comment by chrisdone** [comment]
How's this? Given that `<foo/>`  is a general XML feature, I named it more generally: https://github.com/chrisdone/lucid/commit/e939eccf40747dffd57b861a0f70050f62afae51

**Comment by jeffreyrosenbluth** [comment]
Thats great.
Thanks!

**Comment by chrisdone** [comment]
Okay, bumped to hackage as 2.6.1.

**Comment by chrisdone** [comment]
Fun. blaze is also faster ;)

**Pull request closed without merging**
