### PR TITLE
Bounds + CI for GHC 9.0.1

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
The Travis build doesn't seem to get triggered. Would you like me to generate a Github Actions config instead?

**Comment by chrisdone** [comment]
Sure, thanks!

**Comment by sjakobi** [comment]
@chrisdone I believe you need to turn on actions in Settings->Actions.

**Comment by phadej** [comment]
For some reason, GHA don't run from PR, someone have to commite them into repo first. Let's see if they pass in master.

**Comment by phadej** [comment]
Released in https://hackage.haskell.org/package/lucid-2.9.12.1

**Pull request merged**
